name: Build & Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Build & auto-publish to GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build 